### ISSUE TITLE
opening portfolio pieces

### ISSUE THREAD

**Issue by sara-clayton2** [sara-clayton2/portfolio#10]
Im trying to add code to my portfolio pieces so that when you click on the title of the piece the content opens up. problem is my titles are are within my loop for jekyll so that when i click on the title it opens everything else underneath because it all will have the same class. how would i add individual classes to each title so that its only targeting each individual title ? 

@thomasjbradley

**Comment by thomasjbradley** [comment]
There are a couple things that we'll need to change:
1. Each heading box that you want to be clickable will have to be surrounded in an `<a>` tag.
2. The `<a>` tag `href` needs to point to an ID of the `.content` `<div>`.
3. And you're right, they need completely unique IDs.

So, the simplified HTML will look like this:

``` html
<div class="title">
  <a href="#piece-1">… <!-- but this ID would be replaced with a Jekyll {{portfolio.whatever}} -->
</div>

<div class="content" id="piece-1">… <!-- and this ID too -->
```

Then, you can specify what you want for the ID in side your data file, like:

``` yaml
- title: …
  id: piece-1
```

To make them open and close you need to use CSS `:target`.
http://learn-the-web.algonquindesign.ca/topics/css-animations-effects/#target-pseudo-class

**Comment by sara-clayton2** [comment]
Can you elaborate on this because I did this with my code, but nothing seems to even be targeted and I'm not sure how to do this, sorry. 

![screen shot 2015-11-02 at 2 05 42 pm](https://cloud.githubusercontent.com/assets/6340308/10891262/da084bb8-816a-11e5-8633-da16b3f9e0dc.png)
![screen shot 2015-11-02 at 2 05 19 pm](https://cloud.githubusercontent.com/assets/6340308/10891264/dacdd27a-816a-11e5-8aef-5ee732e372c3.png)
![screen shot 2015-11-02 at 2 05 30 pm](https://cloud.githubusercontent.com/assets/6340308/10891267/dbea265e-816a-11e5-99aa-ad0eb1028bd4.png)

**Comment by thomasjbradley** [comment]
That looks okay to me.
Did you commit and sync it? I can't seem to find it in your code.

**Comment by sara-clayton2** [comment]
yea sorry i just did!

**Comment by thomasjbradley** [comment]
Looking at your data file, I think these two lines should be:
https://github.com/sara-clayton2/portfolio/blob/gh-pages/index.html#L33
https://github.com/sara-clayton2/portfolio/blob/gh-pages/index.html#L41

``` yaml
{{portfolio.id}}
```

You could also simplify your CSS to this:

``` css
.content {
  display: none;
}

.content:target {
  display: block;
}
```

That way it will work for all of them independent of what ID they have.

**Comment by sara-clayton2** [comment]
thanks so much, I really appreciate it! everything works now!
