### ISSUE TITLE
Error message on terminal regarding Jekyll

### ISSUE THREAD

**Issue by sara-clayton2** [sara-clayton2/portfolio#6]
@thomasjbradley 

hey Thomas, I got this error message when I was trying to start my Jekyll stuff for my website. How do I fix it ? 
![screen shot 2015-10-14 at 12 26 20 am](https://cloud.githubusercontent.com/assets/6340308/10474994/ed6a129a-720b-11e5-8133-77fa8407d18a.png)

**Comment by thomasjbradley** [comment]
There's an equals sign missing after the word `baseurl`, this is what you need:

```
jekyll serve --watch --baseurl=""
```

**Comment by sara-clayton2** [comment]
I did that but now Im getting this error 
Also too I didnt realize my terminal wasn't working so I did all the code on my website already with removing the html and doing the looping effects for my content, will that effect anything? 

![screen shot 2015-10-14 at 11 01 19 am](https://cloud.githubusercontent.com/assets/6340308/10487654/fc1c0bf2-7262-11e5-811f-4fdf7e21eb28.png)

**Comment by thomasjbradley** [comment]
Looks like the wrong folder; did you "Open in Terminal" from the GitHub app?

**Comment by sara-clayton2** [comment]
yea I just did that and that errors gone but its still showing up the first error message I have which was this:  


jekyll 2.5.3 | Error:  (/Users/saraclayton/Desktop/Graphic Design 3/Web Development/portfolio/_data/portfolio-pieces.yml): found character that cannot start any token while scanning for the next token at line 1 column 2


I followed the tutorial and my portfolio-pieces.yml  looks like this 
![screen shot 2015-10-14 at 11 31 19 am](https://cloud.githubusercontent.com/assets/6340308/10488540/1fb54ce6-7267-11e5-8e0a-c10442098e70.png)

**Comment by sara-clayton2** [comment]
Fixed that but still getting this error 

![screen shot 2015-10-14 at 11 54 08 am](https://cloud.githubusercontent.com/assets/6340308/10489263/5831a864-726a-11e5-9ead-af1857786826.png)

![screen shot 2015-10-14 at 11 54 21 am](https://cloud.githubusercontent.com/assets/6340308/10489261/56a3ff9c-726a-11e5-8a49-f5fb358b9a87.png)

**Comment by sara-clayton2** [comment]
im not using any tabs only spaces and the paragraphs for the longer content was put into quotation marks as well

**Comment by sara-clayton2** [comment]
I fixed it thanks!

**Comment by thomasjbradley** [comment]
Okay, cool. I was going to suggest the spaces vs. tabs thing.
