### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by sara-clayton2** [sara-clayton2/portfolio#7]
@thomasjbradley 

I don't know whats going on but all the content on my site isn't showing up, i followed the tutorials and set up my portfolio-pieces.yml and config.yml and replaced it in my html document and it won't show up and Im still getting an error I was before

![screen shot 2015-10-14 at 3 31 37 pm](https://cloud.githubusercontent.com/assets/6340308/10495247/ee03b328-7288-11e5-86d0-d595e1cc2a48.png)
![screen shot 2015-10-14 at 3 29 26 pm](https://cloud.githubusercontent.com/assets/6340308/10495245/edfd6de2-7288-11e5-9751-be3d6c76ae22.png)
![screen shot 2015-10-14 at 3 29 18 pm](https://cloud.githubusercontent.com/assets/6340308/10495246/edfd7c24-7288-11e5-8a9a-20d1176647f9.png)

**Comment by thomasjbradley** [comment]
The error message is coming from the very last line of "portfolio-pieces.yml", it isn't indented as much as the line above.
