### ISSUE TITLE
Images in yaml

### ISSUE THREAD

**Issue by sara-clayton2** [sara-clayton2/portfolio#8]
Hi Thomas so I couldn't find in the tutorials how to add images into a yaml file, would I add them in with the rest of my content like : 

![screen shot 2015-10-19 at 3 42 10 pm](https://cloud.githubusercontent.com/assets/6340308/10589220/fac5ca9a-7677-11e5-8c20-c06e4e8dafea.png)

and in html have: 

![screen shot 2015-10-19 at 3 41 39 pm](https://cloud.githubusercontent.com/assets/6340308/10589205/ecd2f87c-7677-11e5-8777-ff77aea794bc.png)

@thomasjbradley

**Comment by sara-clayton2** [comment]
got it never mind! thanks

**Comment by thomasjbradley** [comment]
Cool!
