### ISSUE TITLE
looping 

### ISSUE THREAD

**Issue by sara-clayton2** [sara-clayton2/portfolio#9]
@thomasjbradley

I got all my content to loop properly but looping different images for each is not working. for each image i did a loop around it but now its looking the same image 6 times and the image will not show up. I only have one image for each. 

![screen shot 2015-10-20 at 4 19 53 pm](https://cloud.githubusercontent.com/assets/6340308/10620514/84f9d662-7749-11e5-8ad0-f69d1912b3a2.png)

![screen shot 2015-10-20 at 4 38 42 pm](https://cloud.githubusercontent.com/assets/6340308/10620475/40683d9a-7749-11e5-9a8d-364861392b42.png)
![screen shot 2015-10-20 at 4 38 55 pm](https://cloud.githubusercontent.com/assets/6340308/10620477/40d48342-7749-11e5-90ab-915639871716.png)

**Comment by thomasjbradley** [comment]
Looking at the way the YAML is set up, with a different—single—image for each section, I don't think a loop is necessary. Will each section, like `images-process` have multiple images?

**Comment by sara-clayton2** [comment]
so it would be alright if i were to just do this ? 
![screen shot 2015-10-20 at 4 54 34 pm](https://cloud.githubusercontent.com/assets/6340308/10620847/55061bd0-774b-11e5-9c95-90faaf29a91f.png)
![screen shot 2015-10-20 at 4 54 41 pm](https://cloud.githubusercontent.com/assets/6340308/10620848/57e0a0c8-774b-11e5-94ca-930f4f1f21e3.png)

**Comment by sara-clayton2** [comment]
when creating an alt attribute for each one would it i just create general alt attributes or would i do something like alt="{{portfolio.process-alt}}" and in my yaml do the process-alt: placeholder image ?

**Comment by thomasjbradley** [comment]
The above code makes sense, yeah.

For the alt, I would like to see what you suggest, a different entry for each image because each needs to be described differently for screen readers and SEO.

**Comment by sara-clayton2** [comment]
ok thanks! i ended up doing this: 

img class="placeholder" src="{{portfolio.images-process}}" alt="{{portfolio.images-process-alt}}"

 and In yaml 
   images-process: images/placeholder.svg
   images-process-alt: this will explain my image
